apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: Dispatch Workflows
inputs:
  workflows-dispatch-file:
    description: "Path to the file containing workflow dispatch requests"
    required: true
  token:
    description: "Authorization token to authenticate workflow dispatch requests. It is recommended to pass the token as a secret reference to ensure security."
    required: true
  wait-for-completion:
    description: "Flag to wait for the dispatched workflows to complete"
    required: false
  execution-mode:
    description: "Execution mode for the workflow dispatch request"
    required: false
    default: "parallel"

runs:
  using: "composite"
  steps:
    - id: run-workflow-dispatch-action
      name: "Dispatch Workflows"
      uses: docker://public.ecr.aws/l7o7z1g8/actions/workflow-dispatch-actions:main-c2916e2a079ac65b141500cb8a5a71dc0c7315ed
      shell: sh
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        STEP_ID: ${{ step.internal.id }}
        JOB_ID: ${{ job.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        echo "RUN_ID: $RUN_ID"
        cd /app
        ./workflow-dispatcher dispatch -i '{
          "workflow_dispatch_requests_file":"${{ inputs.workflows-dispatch-file }}",
          "token":"${{ inputs.token }}",
          "wait_for_completion":"${{ inputs.wait-for-completion }}",
          "execution_mode":"${{ inputs.execution-mode }}"
        }'
