= CloudBees action: Dispatch multiple workflows

Use this action to dispatch multiple workflows in the CloudBees platform.

== Prerequisites
* You must link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/personal-access-token#generate[generate a Personal Access Token (PAT) in the CloudBees platform] before invoking this action.
* All workflows to be dispatched must be link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/manage-workflows#create-trigger[manually triggered] workflows.

== Inputs

=== YAML file specifications

The following inputs are for the YAML file:

[cols="2a,1a,1a,3a",options="header"]
.YAML file specifications
|===

| Input name
| Data type
| Required
| Description

| `workflows-dispatch-file`
| String
| Yes
| Path to the <<#json,JSON file>> containing workflow dispatch requests.

| `token`
| String
| Yes
| Authorization token to authenticate workflow dispatch requests.
CloudBees recommends that you pass the token as a link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/configure/properties[secret] reference to ensure security.

| `execution-mode`
| String
| No
| Whether to dispatch all the workflows in parallel or sequentially. Supported values: 'parallel' (default) or 'serial'.

| `wait-for-completion`
| Boolean
| No
| Whether to wait for workflow executions to complete.
Defaults to false when `execution-mode: parallel` is set.
When `execution-mode: serial` is set, is only considered to be true.

|===

[#json]
=== JSON file specifications

The following inputs are for the JSON file:

[cols="2a,1a,1a,3a",options="header"]
.JSON file specifications
|===

| Field
| Data type
| Required
| Description

| `workflow_file_name`
| String
| Yes
| The name of the workflow file to dispatch.

| `branch_name`
| String
| No
| The branch name containing the workflow to dispatch. The default is the same branch as the caller workflow.

| `component_id`
| String
| No
| The link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/organizations-components/components#component-id[ID of the component] containing the manually triggered workflow (located in the platform URL after `componentId=`). The default is the component ID of where the caller workflow is located.

| `inputs`
| Object
| No
| Input parameters to be passed to dispatch the workflow.
Represented as key-value pairs, where keys and values are both strings.

| `ignore_failures`
| Boolean
| No
| Whether to ignore workflow trigger or execution failures.
Default is false.
When both `execution-mode: parallel` and `wait-for-completion: false` are set, is only considered to be true.

|===

== Usage examples

The following summarizes the expected results of using different YAML and JSON specifications in this action.

[cols="1a,1a,4a",options="header"]
.Input examples and results in response to workflow executions.
|===

2+| When the following inputs are specified:
| The following results are observed:

| `execution-mode:`
| `wait-for-completion:`
|

| `parallel`
| `false`
| The action triggers all workflows in parallel.
Once triggered, the action step passes regardless of any failures.
The `ignore-failures` parameter is always considered false for this scenario.

| `parallel`
| `true`
| The action triggers all workflows in parallel, and waits for all triggered runs to complete.
If all runs are successful, the action step passes.
If a dispatched workflow fails in being triggered or executed and has:

* `ignore-failures: true` specified, it does not affect the action step result.
* `ignore-failures: false` specified, the action step fails.

| `serial`
| `true` ^<<footnote1,[1]>>^
| The action triggers each workflow sequentially, so as soon as a workflow run is complete the next workflow is triggered to execute.
If all runs are successful, the action step passes.
If a dispatched workflow fails in being triggered or executed and has:

* `ignore-failures: true` specified, the action step result is not affected by this run, and the action continues on to trigger the next workflow in the series.
* `ignore-failures: false` specified, the action step fails on first failure and subsequent workflows are not triggered.

|===

[#footnote1]
^[1]^ The `wait-for-completion` parameter is always considered true when `execution-mode: serial` is set.

=== Usage example: Default settings

The following example uses the default settings (execution mode: parallel, wait for completion: false).

[source,yaml]
----
    - name: Dispatch workflows
      uses: cloudbees-io/workflows-dispatch@v1
      with:
        workflows-dispatch-file: dispatch_requests.json
        token: "${{ secrets.TOKEN }}"

----

The dispatch_requests.json file for the YAML file above:

[source,json,role="default-expanded"]
----
[
  {
    "workflow_file_name": "workflow-1.yaml"
  },
  {
    "workflow_file_name": "workflow-2.yaml"
  }
]
----

=== Usage example: Await completion of workflow execution

The following action example executes workflows in parallel and waits for completion of all:

[source,yaml]
----
    - name: Dispatch workflows and wait for completion
      uses: cloudbees-io/workflows-dispatch@v1
      with:
        workflows-dispatch-file: dispatch_requests.json
        token: "${{ secrets.TOKEN }}"
        execution-mode: "parallel"
        wait-for-completion: true

----

The dispatch_requests.json file for the example above:

[source,json,role="default-expanded"]
----
[
  {
    "workflow_file_name": "workflow-1.yaml",
    "inputs": {
      "testkey1": "value",
      "testkey2": "50"
    }
  },
  {
    "component_id": "abcdefgh-1234-5678-9abc-defgh1234567",
    "branch_name": "branch-2",
    "workflow_file_name": "workflow-2.yaml"
  }
]
----

=== Usage example: Ignore workflow execution failures

The following action example executes workflows sequentially and ignores failures for one but not the other workflow:

[source,yaml]
----
    - name: Dispatch workflows sequentially and ignore failures
      uses: cloudbees-io/workflows-dispatch@v1
      with:
        workflows-dispatch-file: dispatch_requests.json
        token: "${{ secrets.TOKEN }}"
        execution-mode: "serial"

----

The dispatch_requests.json file for the action example above:

[source,json,role="default-expanded"]
----
[
  {
    "component_id": "12345678-9abc-defg-h123-456789abcdef",
    "branch_name": "branch-1",
    "workflow_file_name": "workflow-1.yaml",
    "inputs": {
      "testkey1": "value",
      "testkey2": "50"
    },
    "ignore_failures": true
  },
  {
    "component_id": "abcdefgh-1234-5678-9abc-defgh1234567",
    "branch_name": "branch-2",
    "workflow_file_name": "workflow-2.yaml",
    "ignore_failures": false
  }
]
----

In the example above, *workflow-2* is executed regardless if *workflow-1* execution has failed, and if *workflow-2* is completed successfully, the action step is passed.
If *workflow-2* fails, the action step is failed.

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
